/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Earth({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/earth.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[0,0,-100]} rotation={[props.rotation.x,props.rotation.y,props.rotation.z]} scale={0.1}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Default OBJ']} />
    </group>
  )
}

useGLTF.preload('/earth.gltf')
