/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Europa({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/europa.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[0,0,-20]} rotation={[0,120,43]}>
      <mesh geometry={nodes._root.geometry} material={materials.transparent}>
        <mesh geometry={nodes.mesh_1.geometry} material={materials.foil_silver} />
        <mesh geometry={nodes.mesh_1_1.geometry} material={materials.dish_foil} />
        <mesh geometry={nodes.Instruments.geometry} material={materials.Material}>
          <mesh geometry={nodes.lens_cover.geometry} material={materials.foil_silver} />
        </mesh>
        <mesh geometry={nodes.mesh_4.geometry} material={materials.Material} />
        <mesh geometry={nodes.mesh_4_1.geometry} material={materials.Lenses} />
        <mesh geometry={nodes.Radiator.geometry} material={materials.Radiator} />
        <mesh geometry={nodes.mesh_6.geometry} material={materials.Material} />
        <mesh geometry={nodes.mesh_6_1.geometry} material={materials.foil_gold} />
        <mesh geometry={nodes.mesh_6_2.geometry} material={materials.shiny_panel} />
        <mesh geometry={nodes.mesh_7.geometry} material={materials.black_krinkle} />
        <mesh geometry={nodes.mesh_7_1.geometry} material={materials.foil_silver} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/europa.gltf')
