/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Nova({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/nova.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.nova_window_R.geometry} material={materials.Glass} />
      <mesh geometry={nodes.nova_doorhandle.geometry} material={materials['Bumper Material']} />
      <mesh geometry={nodes.nova_bumper_F_grille.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_hood_grille.geometry} material={materials['Bumper Material']} />
      <mesh geometry={nodes.nova_hood_grille_cover.geometry} material={materials['Bumper Material']} />
      <mesh geometry={nodes.nova_sideskirt.geometry} material={materials['Main Material']} />
      <mesh geometry={nodes.nova_bumper_F.geometry} material={materials['Bumper Material']} />
      <mesh geometry={nodes.nova_door_F.geometry} material={materials['Main Material']} />
      <mesh geometry={nodes.nova_fender.geometry} material={materials['Main Material']} />
      <mesh geometry={nodes.nova_headlights.geometry} material={materials.Glass} />
      <mesh geometry={nodes.nova_hood.geometry} material={materials['Main Material']} />
      <mesh geometry={nodes.nova_grille.geometry} material={materials['Bumper Material']} />
      <mesh geometry={nodes.nova_bumper_R.geometry} material={materials['Bumper Material']} />
      <mesh geometry={nodes.nova_door_R.geometry} material={materials['Main Material']} />
      <mesh geometry={nodes.nova_taillights.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Main Material']} />
      <mesh geometry={nodes.Plane007_1.geometry} material={materials.Chasis} />
      <mesh geometry={nodes.nova_tailgate.geometry} material={materials['Main Material']} />
      <mesh geometry={nodes.nova_badge.geometry} material={nodes.nova_badge.material} />
      <mesh geometry={nodes.nova_windshield_F.geometry} material={materials.Glass} />
      <mesh geometry={nodes.nova_window_F.geometry} material={materials.Glass} />
      <mesh geometry={nodes.nova_windshield_R.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Plane022.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.Plane022_1.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.nova_lock_R.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_seat_F.geometry} material={materials.Seats} />
      <mesh geometry={nodes.nova_steering_wheel.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_seat_R.geometry} material={materials.Seats} />
      <mesh geometry={nodes.nova_dashboard.geometry} material={materials.Dashboard} />
      <mesh geometry={nodes.nova_gear_shifter.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_wiper_stick.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_steeringwheel_base.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_interior_grills.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_steering_rack.geometry} material={materials.Metal} />
      <mesh geometry={nodes.nova_slider.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_button_a.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_button_b.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_button_d.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_button_c.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_indicator_stick.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_exhaust.geometry} material={materials.Metal} />
      <mesh geometry={nodes.nova_exhaust_muffler.geometry} material={materials.Metal} />
      <mesh geometry={nodes.nova_windshield_nozzle.geometry} material={nodes.nova_windshield_nozzle.material} />
      <mesh geometry={nodes.nova_rearview.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_button_e.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.nova_carb_starter.geometry} material={nodes.nova_carb_starter.material} />
    </group>
  )
}

useGLTF.preload('/nova.glb')
