/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: wallon (https://sketchfab.com/realwallon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mazda-rx-7-45cb02e634ed477a9a04bb19813443f2
title: Mazda RX-7
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Car({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={1} rotation={[0,-0.5,0]} position={[3,-5,-10]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane001_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane002_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane003_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane004_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane006_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane007_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane005_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane008_Glasswindow_0.geometry} material={materials.Glasswindow} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane009_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Headlight_Cases_Glasswindow_0.geometry} material={materials.Glasswindow} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane011_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane012_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane013_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane014_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane015_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane016_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Headlight_Case_2_Glasswindow_0.geometry} material={materials.Glasswindow} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane020_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane021_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane023_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane028_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane029_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.headlight_Case_3_Glasswindow_0.geometry} material={materials.Glasswindow} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane032_Glasswindow_0.geometry} material={materials.Glasswindow} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube001_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube002_Chrome_Parts_0.geometry} material={materials.Chrome_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane033_Glasswindow_0.geometry} material={materials.Glasswindow} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane034_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Headlight_Glass_Headlight_textures_0.geometry} material={materials.Headlight_textures} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Chrome_Parts_Chrome_Parts_0.geometry} material={materials.Chrome_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane037_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane038_Chrome_Parts_0.geometry} material={materials.Chrome_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder_Chrome_Parts_0.geometry} material={materials.Chrome_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane039_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane041_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube003_Pure_Black_0.geometry} material={materials.Pure_Black} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube004_Pure_Black_0.geometry} material={materials.Pure_Black} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Torus_Pure_Black_0.geometry} material={materials.Pure_Black} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane043_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube005_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane044_Car_body_0.geometry} material={materials.Car_body} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube006_Pure_Black_0.geometry} material={materials.Pure_Black} />
          </group>
          <group position={[199.78, 268.14, 22.91]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.rear_left_wheel_wheel_0.geometry} material={materials.wheel} />
          </group>
          <group position={[187.08, 268.14, 643.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.front_left_wheel_wheel_0.geometry} material={materials.wheel} />
          </group>
          <group position={[-187.08, 268.14, 643.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.front_right_wheel_wheel_0.geometry} material={materials.wheel} />
          </group>
          <group position={[-199.78, 268.14, 22.91]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.rear_right_wheel_wheel_0.geometry} material={materials.wheel} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube007_Black_Parts_0.geometry} material={materials.Black_Parts} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.intercooler_intercooler_0.geometry} material={materials.intercooler} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
