/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BlockedGravity (https://sketchfab.com/blockedgravity)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/little-planet-earth-d54bb387f62147dcbf4be0605068b1cc
title: Little Planet Earth
*/


import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('static/planet.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -500]}>
            <mesh geometry={nodes.Clouds_2_Clouds_1.geometry} material={materials.Clouds} />
          </group>
          <group position={[0, 0, -500]}>
            <mesh geometry={nodes.Ocean_Mat_0.geometry} material={materials.material} />
          </group>
          <group position={[-64.3, 10.84, -5]}>
            <mesh geometry={nodes.CONT_Extrude_Mat3_0.geometry} material={materials['Mat.3']} />
          </group>
          <group position={[0, 500, -500]}>
            <mesh geometry={nodes.SP_Extrude_Ice_0.geometry} material={materials.material_3} />
          </group>
          <group position={[0, -500, -500]}>
            <mesh geometry={nodes.NP_Extrude_Ice_0.geometry} material={materials.material_3} />
          </group>
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('static/planet.gltf')
