/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ivan Norman (https://sketchfab.com/vanidza)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/low-poly-truck-car-drifter-f3750246b6564607afbefc61cb1683b1
title: Low-poly truck (car "Drifter")
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="7f09d404031140d78a7bb6db74b81fa4fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Spring" position={[155.62, 20.72, -81.96]} rotation={[-0.21, Math.PI / 2, 0]} scale={2.8}>
                  <mesh name="Spring_Light_black_0" geometry={nodes.Spring_Light_black_0.geometry} material={materials.Light_black} />
                  <mesh name="Spring_Black_0" geometry={nodes.Spring_Black_0.geometry} material={materials.Black} />
                </group>
                <group name="Spring001" position={[-128.51, 20.72, -81.96]} rotation={[-0.21, Math.PI / 2, 0]} scale={2.8}>
                  <mesh name="Spring001_Light_black_0" geometry={nodes.Spring001_Light_black_0.geometry} material={materials.Light_black} />
                  <mesh name="Spring001_Black_0" geometry={nodes.Spring001_Black_0.geometry} material={materials.Black} />
                </group>
                <group name="Spring002" position={[155.62, 20.72, 81.96]} rotation={[0.21, -Math.PI / 2, 0]} scale={2.8}>
                  <mesh name="Spring002_Light_black_0" geometry={nodes.Spring002_Light_black_0.geometry} material={materials.Light_black} />
                  <mesh name="Spring002_Black_0" geometry={nodes.Spring002_Black_0.geometry} material={materials.Black} />
                </group>
                <group name="Spring003" position={[-128.51, 20.72, 81.96]} rotation={[0.21, -Math.PI / 2, 0]} scale={2.8}>
                  <mesh name="Spring003_Light_black_0" geometry={nodes.Spring003_Light_black_0.geometry} material={materials.Light_black} />
                  <mesh name="Spring003_Black_0" geometry={nodes.Spring003_Black_0.geometry} material={materials.Black} />
                </group>
                <group name="Smoke001" position={[70.41, 165.26, 94.26]} scale={0}>
                  <mesh name="Smoke001_Smoke_0" geometry={nodes.Smoke001_Smoke_0.geometry} material={materials.Smoke} />
                </group>
                <group name="Smoke002" position={[74.6, 165.67, 92.36]} scale={0}>
                  <mesh name="Smoke002_Smoke_0" geometry={nodes.Smoke002_Smoke_0.geometry} material={materials.Smoke} />
                </group>
                <group name="Smoke003" position={[72.18, 166.53, 95.14]} scale={0}>
                  <mesh name="Smoke003_Smoke_0" geometry={nodes.Smoke003_Smoke_0.geometry} material={materials.Smoke} />
                </group>
                <group name="Smoke004" position={[73.14, 165.64, 93.1]} scale={0}>
                  <mesh name="Smoke004_Smoke_0" geometry={nodes.Smoke004_Smoke_0.geometry} material={materials.Smoke} />
                </group>
                <group name="Smoke005" position={[75.2, 166.04, 95.17]} scale={0}>
                  <mesh name="Smoke005_Smoke_0" geometry={nodes.Smoke005_Smoke_0.geometry} material={materials.Smoke} />
                </group>
                <group name="Smoke006" position={[75.86, 167.36, 89.87]} scale={0}>
                  <mesh name="Smoke006_Smoke_0" geometry={nodes.Smoke006_Smoke_0.geometry} material={materials.Smoke} />
                </group>
                <group name="Smoke007" position={[74.99, 167.94, 90.93]} scale={0}>
                  <mesh name="Smoke007_Smoke_0" geometry={nodes.Smoke007_Smoke_0.geometry} material={materials.Smoke} />
                </group>
                <group name="Smoke008" position={[73.57, 166.39, 94.53]} scale={0}>
                  <mesh name="Smoke008_Smoke_0" geometry={nodes.Smoke008_Smoke_0.geometry} material={materials.Smoke} />
                </group>
                <group name="Smoke009" position={[70.76, 159.59, 95.08]} scale={0}>
                  <mesh name="Smoke009_Smoke_0" geometry={nodes.Smoke009_Smoke_0.geometry} material={materials.Smoke} />
                </group>
                <group name="Smoke010" position={[72.88, 163.49, 92.99]} scale={0}>
                  <mesh name="Smoke010_Smoke_0" geometry={nodes.Smoke010_Smoke_0.geometry} material={materials.Smoke} />
                </group>
                <group name="Smoke011" position={[75.05, 162.61, 91.64]} scale={0}>
                  <mesh name="Smoke011_Smoke_0" geometry={nodes.Smoke011_Smoke_0.geometry} material={materials.Smoke} />
                </group>
                <group name="Smoke012" position={[73.82, 161.82, 89.95]} scale={0}>
                  <mesh name="Smoke012_Smoke_0" geometry={nodes.Smoke012_Smoke_0.geometry} material={materials.Smoke} />
                </group>
                <group name="Frame" rotation={[-Math.PI / 2, 0, 0]} scale={[300, 100, 50]}>
                  <mesh name="Frame_Orange_0" geometry={nodes.Frame_Orange_0.geometry} material={materials.Orange} />
                  <mesh name="Frame_Black_0" geometry={nodes.Frame_Black_0.geometry} material={materials.Black} />
                  <mesh name="Frame_Glass_0" geometry={nodes.Frame_Glass_0.geometry} material={materials.Glass} />
                  <mesh name="Frame_Light_0" geometry={nodes.Frame_Light_0.geometry} material={materials.Light} />
                  <mesh name="Frame_Light_red_0" geometry={nodes.Frame_Light_red_0.geometry} material={materials.Light_red} />
                  <mesh name="Frame_Dark_brown_0" geometry={nodes.Frame_Dark_brown_0.geometry} material={materials.Dark_brown} />
                  <mesh name="Frame_Dark_brown_handle_0" geometry={nodes.Frame_Dark_brown_handle_0.geometry} material={materials.Dark_brown_handle} />
                  <mesh name="Frame_Glass_trailer_0" geometry={nodes.Frame_Glass_trailer_0.geometry} material={materials.Glass_trailer} />
                  <mesh name="Frame_Light_black_0" geometry={nodes.Frame_Light_black_0.geometry} material={materials.Light_black} />
                  <mesh name="Frame_Brown_0" geometry={nodes.Frame_Brown_0.geometry} material={materials.Brown} />
                </group>
                <group name="Front_wheel" position={[155.62, 9.27, -127.28]} rotation={[0, 0, -1.4]} scale={[50.1, 50.1, 27.01]}>
                  <mesh name="Front_wheel_Black_0" geometry={nodes.Front_wheel_Black_0.geometry} material={materials.Black} />
                  <mesh name="Front_wheel_Light_black_0" geometry={nodes.Front_wheel_Light_black_0.geometry} material={materials.Light_black} />
                </group>
                <group name="Rear_wheel" position={[-128.51, 14.27, -125.98]} rotation={[0, 0, -2.16]} scale={[55.11, 55.11, 29.62]}>
                  <mesh name="Rear_wheel_Black_0" geometry={nodes.Rear_wheel_Black_0.geometry} material={materials.Black} />
                  <mesh name="Rear_wheel_Light_black_0" geometry={nodes.Rear_wheel_Light_black_0.geometry} material={materials.Light_black} />
                </group>
                <group name="Front_wheel001" position={[155.62, 9.27, 127.28]} rotation={[Math.PI, 0, 1.31]} scale={[50.1, 50.1, 27.01]}>
                  <mesh name="Front_wheel001_Black_0" geometry={nodes.Front_wheel001_Black_0.geometry} material={materials.Black} />
                  <mesh name="Front_wheel001_Light_black_0" geometry={nodes.Front_wheel001_Light_black_0.geometry} material={materials.Light_black} />
                </group>
                <group name="Rear_wheel001" position={[-128.51, 14.27, 125.98]} rotation={[Math.PI, 0, 2.13]} scale={[55.11, 55.11, 29.62]}>
                  <mesh name="Rear_wheel001_Black_0" geometry={nodes.Rear_wheel001_Black_0.geometry} material={materials.Black} />
                  <mesh name="Rear_wheel001_Light_black_0" geometry={nodes.Rear_wheel001_Light_black_0.geometry} material={materials.Light_black} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
